name: Front build

on:
  push:
    branches: [master, deploy]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: DockerHub login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: Create Builder, application images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_REPO }}:latest  .

      - name: Push application images
        run: |
          docker push ${{ secrets.DOCKERHUB_REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: pulling application images
        uses: appleboy/ssh-action@master
        with:
          envs: GITHUB_SHA
          host: ${{ secrets.BACK_HOST }}
          username: ${{ secrets.BACK_USER }}
          password: ${{ secrets.BACK_PASSWORD }}
          script: |
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
            cd front_diplom/
            docker pull ${{ secrets.DOCKERHUB_REPO }}:latest
            export APICONTID=$(docker ps -q --filter "name=front_react")
            docker stop $APICONTID
            docker rm $APICONTID
            docker run -d  --network host --name front_react ${{ secrets.DOCKERHUB_REPO }}:latest
            docker container prune -f
            docker image prune -f
